Repository newrelic/newrelic-client-go, pull requests merged in 2020-12, with the labels that each got.

#560 Updating from current NerdGraph Schema
  .github/workflows/test.yml
  .tutone.yml
  go.mod
  go.sum
  pkg/accounts/types.go
  pkg/alerts/nrql_conditions.go
  pkg/alerts/nrql_conditions_integration_test.go
  pkg/alerts/types.go
  pkg/apiaccess/keys.go
  pkg/apiaccess/types.go
  pkg/edge/trace_observers.go
  pkg/edge/types.go
  pkg/eventstometrics/eventstometrics_integration_test.go
  pkg/eventstometrics/example_basic_test.go
  pkg/eventstometrics/types.go
  pkg/nrdb/example_query_test.go
  pkg/nrdb/nrdb_integration_test.go
  pkg/nrdb/nrdb_query.go
  pkg/nrdb/types.go
  templates/typegen/types.go.tmpl
Labels: breaking-change, enhancement, priority:high, refactor, size:L

#569 refs/tags/v0.52.0 Changelog Update
  CHANGELOG.md
Labels: automated pr, changelog

#567 Auto-gen cleanup / fix for existing generated packages
  .tutone.yml
  go.mod
  go.sum
  pkg/accounts/types.go
  pkg/alerts/types.go
  pkg/apiaccess/types.go
  pkg/cloud/cloud_api.go
  pkg/cloud/cloud_api_integration_test.go
  pkg/cloud/example_cloud_account_test.go
  pkg/cloud/types.go
  pkg/edge/types.go
  pkg/entities/entity.go
  pkg/entities/tags.go
  pkg/entities/types.go
  pkg/eventstometrics/types.go
  pkg/infrastructure/types.go
  pkg/nerdstorage/types.go
  pkg/nrdb/types.go
  pkg/nrtime/types.go
  pkg/nrtime/types_func.go
  templates/nerdgraphclient/client.go.tmpl
  templates/typegen/types.go.tmpl
Labels: enhancement

#571 chore(tutone): update generated code
  pkg/entities/types.go
Labels: enhancement

#573 chore(tutone): update generated code
  pkg/entities/types.go
Labels: enhancement

#578 chore(tutone): update generated code
  pkg/entities/types.go
Labels: enhancement

#575 Code Generate Entities
  .tutone.yml
  go.mod
  go.sum
  newrelic/example_basic_test.go
  pkg/apiaccess/types.go
  pkg/cloud/cloud_api.go
  pkg/cloud/types.go
  pkg/entities/entities_api.go
  pkg/entities/entity.go
  pkg/entities/entity_integration_test.go
  pkg/entities/example_entity_test.go
  pkg/entities/example_tags_test.go
  pkg/entities/tags.go
  pkg/entities/tags_integration_test.go
  pkg/entities/types.go
  pkg/nrdb/types.go
  pkg/nrtime/types_func.go
  templates/typegen/types.go.tmpl
Labels: enhancement, priority:high, refactor, size:XL

#579 Auto-generate code for GraphQL dashboard API
  .tutone.yml
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboard_integration_test.go
  pkg/dashboards/dashboards_api.go
  pkg/dashboards/dashboards_api_integration_test.go
  pkg/dashboards/types.go
  pkg/entities/entity.go
  pkg/entities/types.go
Labels: enhancement, priority:high, size:L

#581 chore(changelog): Update CHANGELOG for v0.53.0
  CHANGELOG.md
  internal/version/version.go
Labels: changelog, enhancement

#583 refs/tags/v0.53.0 Changelog Update
  go.sum
Labels: automated pr, changelog
