Repository newrelic/newrelic-client-go, pull requests merged in 2020-01, with the labels that each got.

#71 bug: Change Infra alert condition value to float
  pkg/alerts/infrastructure_conditions_test.go
  pkg/alerts/infrastructure_conditions_types.go
Labels: bug

#83 Add Snyk scanning
  .circleci/config.yml
Labels: priority:high, size:S

#90 Disable snyk issues to fail the build on CircleCI
  .circleci/config.yml
Labels: priority:blocker, size:S

#102 fix(alerts): custom unmarshal of channel configuration Headers and Payload fields
  pkg/alerts/alerts_types.go
  pkg/alerts/channels_integration_test.go
  pkg/alerts/channels_test.go
Labels: bug
