Repository newrelic/newrelic-client-go, pull requests merged in 2020-03, with the labels that each got.

#158 Omit ApplicationID if not returned
  pkg/entities/entity.go
Labels: bug

#160 fix(http): create a new errorValue for every request
  internal/http/client.go
  internal/http/client_test.go
  internal/http/errors.go
  internal/http/graphql_client.go
  pkg/infrastructure/infrastructure.go
  pkg/synthetics/synthetics.go
Labels: bug

#171 CI Improvements
  .circleci/config.yml
  .gitignore
  .goreleaser.yml
  Makefile
  build/compile.mk
  build/docker.mk
  build/document.mk
  build/lint.mk
  build/release.mk
  build/test.mk
  cmd/.keep
  go.mod
  go.sum
  pkg/apm/apm.go
  scripts/release.sh
  tools.go
Labels: dependencies, refactor, size:M

#172 refactor: remove transient PolicyID on conditions structs for 1:1 mapping to API responses
  pkg/alerts/conditions.go
  pkg/alerts/conditions_integration_test.go
  pkg/alerts/conditions_test.go
  pkg/alerts/nrql_conditions.go
  pkg/alerts/nrql_conditions_integration_test.go
  pkg/alerts/nrql_conditions_test.go
  pkg/alerts/plugins_conditions.go
  pkg/alerts/plugins_conditions_integration_test.go
  pkg/alerts/plugins_conditions_test.go
Labels: breaking-change

#179 fix(build): Force pull tags after each checkout
  .circleci/config.yml
Labels: bug, size:S

#180 Expand data returned by `entity`, make search/fetch consistent
  pkg/entities/entity.go
  pkg/entities/entity_integration_test.go
Labels: breaking-change, enhancement, refactor, size:M

#187 refactor: Consolidate HTTP Clients
  internal/http/client.go
  internal/http/client_test.go
  internal/http/graphql.go
  internal/http/graphql_client.go
  internal/http/request.go
  internal/http/test_helpers.go
  pkg/alerts/alerts.go
  pkg/alerts/alerts_test.go
  pkg/apm/apm.go
  pkg/apm/applications.go
  pkg/apm/applications_rest.go
  pkg/apm/deployments.go
  pkg/dashboards/dashboards.go
  pkg/entities/entities.go
  pkg/entities/entities_test.go
  pkg/infrastructure/infrastructure_test.go
  pkg/nerdgraph/nerdgraph.go
  pkg/plugins/components_integration_test.go
  pkg/plugins/plugins.go
  pkg/synthetics/synthetics.go
  pkg/synthetics/synthetics_test.go
Labels: refactor, size:XL

#191 Build: Add goimports
  build/lint.mk
  go.mod
  go.sum
  internal/http/request.go
  pkg/alerts/conditions_integration_test.go
  pkg/alerts/infrastructure_conditions_integration_test.go
  pkg/alerts/infrastructure_conditions_test.go
  pkg/alerts/multi_location_synthetics_conditions_integration_test.go
  pkg/alerts/nrql_conditions_integration_test.go
  pkg/alerts/plugins_conditions_integration_test.go
  pkg/alerts/policies_integration_test.go
  pkg/alerts/policies_test.go
  pkg/alerts/policy_channels_integration_test.go
  pkg/alerts/synthetics_conditions.go
  pkg/alerts/synthetics_conditions_integration_test.go
  pkg/apm/labels_integration_test.go
  pkg/dashboards/dashboard_integration_test.go
  pkg/dashboards/dashboards_test.go
  pkg/nerdgraph/nerdgraph_integration_test.go
  pkg/plugins/components_integration_test.go
  pkg/plugins/plugins_test.go
  pkg/synthetics/monitor_labels_integration_test.go
  pkg/synthetics/monitor_scripts_integration_test.go
  pkg/synthetics/monitors_integration_test.go
  pkg/synthetics/secure_credentials_integration_test.go
  tools.go
Labels: dependencies, enhancement, priority:medium, size:S

#194 fix(workloads): use epoch time for EntitySearchQuery.CreatedAt
  pkg/workloads/workload.go
  pkg/workloads/workload_integration_test.go
Labels: bug

#195 fix(alerts) add custom unmarshaling for ConditionTerm
  pkg/alerts/conditions_test.go
  pkg/alerts/serialization.go
Labels: bug

#218 chore(docs): Add CLA assistant badge
  README.md
Labels: documentation, size:S

#217 chore(deps): Renovate to ignore golang.org/x/tools (changes constantly)
  .github/renovate.json
Labels: dependencies

#222 Reorganize typegen code in repo
  build/deps.mk
  build/generate.mk
  etc/typegen.yaml
  pkg/alerts/alerts.go
  pkg/alerts/typegen.yaml
  tools/tools.go
  tools/typegen/main.go
Labels: refactor

#227 docs(README): Update example in README, closes #225
  README.md
Labels: documentation
