Repository newrelic/newrelic-client-go, pull requests merged in 2020-06, with the labels that each got.

#336 feat(alerts): implement NerdGraph methods for outlier NRQL alert conditions
  pkg/alerts/nrql_conditions.go
  pkg/alerts/nrql_conditions_integration_test.go
Labels: enhancement

#345 NRDB Queries
  .github/renovate.json
  build/lint.mk
  go.mod
  go.sum
  newrelic/newrelic.go
  pkg/nerdgraph/nerdgraph.go
  pkg/nrdb/doc.go
  pkg/nrdb/example_query_test.go
  pkg/nrdb/nrdb.go
  pkg/nrdb/nrdb_integration_test.go
  pkg/nrdb/typegen.yaml
  pkg/nrdb/types.go
  tools/typegen/README.md
  tools/typegen/main.go
  tools/typegen/typegen.go
Labels: enhancement, priority:medium, size:M

#352 feat(nrdb): Fetch nrql query history
  pkg/nrdb/nrdb.go
  pkg/nrdb/nrdb_integration_test.go
  pkg/nrdb/nrdb_query.go
  pkg/nrdb/typegen.yaml
  pkg/nrdb/types.go
  pkg/nrdb/types_func.go
Labels: enhancement

#353 chore(changelog): Update CHANGELOG for v0.30.0
  CHANGELOG.md
  internal/version/version.go
Labels: enhancement

#354 fix(deps): revert goreleaser v0.138.0 (causing import issues)
  go.mod
  go.sum
Labels: bug, priority:blocker, size:S

#357 fix(serialization): set location to UTC, fix nanosecond handling
  internal/serialization/epoch_time.go
  internal/serialization/epoch_time_test.go
  pkg/alerts/policies_test.go
  pkg/nrdb/types_func.go
Labels: bug, enhancement, priority:medium, size:S

#358 chore(changelog): Update CHANGELOG for v0.30.2
  CHANGELOG.md
  internal/version/version.go
Labels: bug
