Repository newrelic/newrelic-client-go, pull requests merged in 2020-04, with the labels that each got.

#242 Fix: goreleaser now with real library support
  .goreleaser.yml
  go.mod
  go.sum
Labels: dependencies, refactor

#244 Typegen Refactor
  pkg/alerts/alerts.go
  pkg/alerts/typegen.yaml
  pkg/alerts/types.go
  pkg/nerdgraph/nerdgraph.go
  tools/typegen/main.go
  tools/typegen/schema.go
  tools/typegen/typegen.go
Labels: refactor, size:M

#247 Split parsing / fetching of region data
  internal/testing/config.go
  newrelic/newrelic.go
  pkg/config/config.go
  pkg/region/errors.go
  pkg/region/errors_test.go
  pkg/region/region.go
  pkg/region/region_constants.go
  pkg/region/region_test.go
Labels: refactor

#248 chore(changelog): Update CHANGELOG for v0.21.0
  CHANGELOG.md
  internal/version/version.go
Labels: size:S

#259 chore(build): Add Github Actions config
  .github/workflows/release.yml
  .github/workflows/security.yml
  .github/workflows/test.yml
  internal/version/version_test.go
Labels: refactor, size:M

#267 chore(dashboards): add enum for grid column count
  pkg/dashboards/dashboard_integration_test.go
  pkg/dashboards/dashboards_types.go
Labels: enhancement, priority:high, product:Insights, size:S

#268 Dep Updates
  go.mod
  go.sum
Labels: dependencies, size:S

#269 chore(changelog): Update CHANGELOG for v0.22.0
  CHANGELOG.md
  internal/version/version.go
Labels: enhancement, priority:medium, size:S

#270 chore(build): Cleanup release process to include GH changelog generation
  .goreleaser.yml
  build/document.mk
  build/release.mk
Labels: enhancement

#271 chore(build): Remove CircleCI config and update README badges
  .circleci/config.yml
  README.md
Labels: documentation, refactor, size:S

#275 refactor(build): Split up github actions a bit
  .github/workflows/compile.yml
  .github/workflows/test.yml
Labels: refactor

#277 typegen refactor
  pkg/alerts/typegen.yaml
  pkg/alerts/types.go
  tools/typegen/README.md
  tools/typegen/main.go
  tools/typegen/query.go
  tools/typegen/schema.go
  tools/typegen/typegen.go
  tools/typegen/types.go
Labels: refactor, size:M

#278 fix(workloads): Removing deprecated field `name` from `entitySearchQuery`
  pkg/workloads/workload.go
Labels: size:S

#279 Fix: Github Actions needs full history to lint commit messages
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: bug, size:S
