Repository newrelic/newrelic-client-go, pull requests merged in 2020-05, with the labels that each got.

#282 chore(deps): Update tools and linter
  go.mod
  go.sum
Labels: dependencies, size:S

#283 Release v0.23.0
  CHANGELOG.md
  internal/version/version.go
Labels: enhancement, size:S

#287 fix(alerts): Alerts paging was incorrectly generating URLs
  pkg/alerts/channels.go
  pkg/alerts/conditions.go
  pkg/alerts/incidents.go
  pkg/alerts/multi_location_synthetics_conditions.go
  pkg/alerts/nrql_conditions.go
  pkg/alerts/plugins_conditions.go
  pkg/alerts/synthetics_conditions.go
Labels: bug, priority:blocker, size:M

#288 chore(changelog): Update CHANGELOG for v0.23.1
  CHANGELOG.md
  internal/version/version.go
Labels: priority:high, size:S

#289 chore(docs): Add NR Open Source header
  README.md
Labels: documentation

#302 fix(alerts): allow blank runbook URL to be sent
  pkg/alerts/conditions.go
Labels: bug

#304 feat(edge): add trace observer resource
  newrelic/newrelic.go
  pkg/alerts/policies_integration_test.go
  pkg/alerts/types.go
  pkg/edge/doc.go
  pkg/edge/edge.go
  pkg/edge/example_trace_observer_test.go
  pkg/edge/trace_observers.go
  pkg/edge/trace_observers_integration_test.go
  pkg/edge/typegen.yaml
  pkg/edge/types.go
  tools/typegen/typegen.go
Labels: enhancement, size:M

#306 chore(build): No more pre-releases by default
  .goreleaser.yml
Labels: documentation, size:S

#307 chore(changelog): Update CHANGELOG for v0.24.0
  CHANGELOG.md
  internal/version/version.go
Labels: enhancement

#308 Update GH Action to fix release notes
  .githooks/commit-msg
  .githooks/pre-commit
  .githooks/pre-push
  .github/workflows/release.yml
  Makefile
  build/document.mk
  build/release.mk
  build/util.mk
  go.mod
  go.sum
Labels: bug, documentation, size:S

#322 HTTP Compression / Prep for Insights
  internal/http/auth.go
  internal/http/client.go
  internal/http/client_test.go
  internal/http/compress.go
  internal/http/compress_test.go
  internal/http/request.go
  pkg/config/compression.go
  pkg/config/config.go
  pkg/region/region.go
  pkg/region/region_constants.go
  pkg/synthetics/monitor_labels.go
Labels: enhancement, priority:medium, size:M

#324 Update deps
  go.mod
  go.sum
Labels: dependencies, priority:medium, size:S

#325 Use default User-Agent header if none provided
  internal/http/request.go
  pkg/config/config.go
Labels: bug, priority:medium, size:S

#326 chore(changelog): Update CHANGELOG for v0.26.0
  CHANGELOG.md
  internal/version/version.go
Labels: priority:medium, size:S

#332 [fix]: EpochTime Serialization with Milliseconds
  internal/serialization/epoch_time.go
  internal/serialization/epoch_time_test.go
  pkg/alerts/infrastructure_conditions_test.go
  pkg/alerts/policies_test.go
Labels: bug, priority:high, refactor, size:M
