Repository newrelic/newrelic-client-go, pull requests merged in 2021-01, with the labels that each got.

#588 chore(tutone): update generated code
  pkg/dashboards/dashboards_api.go
  pkg/entities/entities_api.go
  pkg/entities/types.go
Labels: enhancement

#590 Entity Getters + Increased requirements for EntityInterface
  .tutone.yml
  go.mod
  go.sum
  pkg/entities/types.go
  templates/typegen/types.go.tmpl
Labels: enhancement, priority:high, size:L

#592 chore(changelog): Update CHANGELOG for v0.54.0
  CHANGELOG.md
  internal/version/version.go
Labels: priority:high, refactor, size:S

#593 chore(tools): move dep tracking for tools to tools package
  build/deps.mk
  build/document.mk
  build/generate.mk
  build/lint.mk
  build/release.mk
  build/test.mk
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: dependencies

#595 feat(entities): Add more methods to Entity(Outline)Interface
  .tutone.yml
  pkg/entities/types.go
Labels: enhancement

#602 fix(dashboards): DashboardWidgetConfigurationInput needs to be nullable
  README.md
  pkg/dashboards/dashboards_api_integration_test.go
  pkg/dashboards/types.go
  pkg/testhelpers/config.go
Labels: priority:blocker

#604 chore(changelog): Update CHANGELOG for v0.55.1
  CHANGELOG.md
  internal/version/version.go
Labels: priority:blocker

#607 fix(dashboards): remove manual changes so code generation works again
  .tutone.yml
  pkg/dashboards/types.go
Labels: priority:blocker, refactor, size:S

#609 chore(changelog): Update CHANGELOG for v0.55.3
  CHANGELOG.md
  internal/version/version.go
Labels: bug, priority:blocker

#610 chore(tutone): update generated code
  pkg/alerts/types.go
Labels: enhancement

#577 chore: update to readme
  README.md
Labels: documentation

#622 Update dashboards API
  Makefile
  build/deps.mk
  build/lint.mk
  build/tools.mk
  go.sum
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboards_api.go
  pkg/dashboards/types.go
  tools/go.mod
  tools/go.sum
Labels: breaking-change, priority:blocker

#624 chore(changelog): Update CHANGELOG for v0.55.6
  CHANGELOG.md
  internal/version/version.go
Labels: priority:blocker

#623 chore(tutone): update generated code
  pkg/entities/types.go
Labels: enhancement

#625 chore(changelog): Update CHANGELOG for v0.55.7
  CHANGELOG.md
  internal/version/version.go
Labels: breaking-change, priority:blocker, size:S

#626 refactor(dashboards): Use nrqlQueries in place of queries
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboards_api_integration_test.go
  pkg/workloads/workload_integration_test.go
Labels: beta, breaking-change, priority:blocker, refactor

#628 chore(changelog): Update CHANGELOG for v0.55.8
  CHANGELOG.md
  internal/version/version.go
Labels: priority:blocker

#633 chore(tutone): update generated code
  pkg/dashboards/types.go
  pkg/entities/types.go
Labels: enhancement

#639 refactor(testhelpers): Remove hard-coded TestAccountID
  README.md
  pkg/alerts/nrql_conditions_integration_test.go
  pkg/apiaccess/keys_integration_test.go
  pkg/cloud/cloud_api_integration_test.go
  pkg/cloud/example_cloud_account_test.go
  pkg/dashboards/dashboards_api_integration_test.go
  pkg/events/events_integration_test.go
  pkg/events/example_basic_test.go
  pkg/events/example_batch_test.go
  pkg/eventstometrics/eventstometrics_integration_test.go
  pkg/nerdstorage/nerdstorage_integration_test.go
  pkg/testhelpers/helpers.go
Labels: priority:medium, refactor, size:M

#642 Dashboards: Include permalink in fetch
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboards_integration_test.go
Labels: bug, size:S

#643 chore(changelog): Update CHANGELOG for v0.56.2
  CHANGELOG.md
  internal/version/version.go
Labels: bug, priority:blocker, size:S

#646 fix(dashboards): MANUAL CHANGE: remove queries until it is out of the schema
  pkg/dashboards/dashboards_api.go
  pkg/dashboards/types.go
Labels: beta, breaking-change, bug

#648 feat(users): Add users package
  .tutone.yml
  pkg/apiaccess/types.go
  pkg/entities/types.go
  pkg/users/doc.go
  pkg/users/example_users_test.go
  pkg/users/types.go
  pkg/users/users.go
  pkg/users/users_api.go
  pkg/users/users_integration_test.go
  pkg/workloads/workload.go
  tools/go.mod
  tools/go.sum
Labels: enhancement, refactor, size:S

#650 chore(changelog): Update CHANGELOG for v0.57.0
  CHANGELOG.md
  internal/version/version.go
Labels: priority:high

#654 chore(testhelpers): Ensure logging, increase timeouts
  pkg/testhelpers/config.go
Labels: priority:medium, size:S

#656 refactor: Tutone auto-naming conflict with schema
  pkg/cloud/cloud_api.go
  pkg/dashboards/dashboards_api.go
  pkg/entities/entities_api.go
  templates/nerdgraphclient/client.go.tmpl
Labels: priority:medium, size:M

#657 refs/tags/v0.57.1 Changelog Update
  CHANGELOG.md
Labels: automated pr, changelog
