Repository newrelic/newrelic-client-go, pull requests merged in 2021-02, with the labels that each got.

#658 refs/tags/v0.57.2 Changelog Update
  CHANGELOG.md
Labels: automated pr, changelog

#668 Fix interface unmarshal on empty / null values
  pkg/apiaccess/types.go
  pkg/cloud/types.go
  pkg/edge/types.go
  pkg/entities/types.go
  pkg/nrdb/types.go
  templates/typegen/types.go.tmpl
Labels: bug, priority:blocker, size:S

#669 chore(tutone): update generated code
  tools/go.sum
Labels: enhancement

#664 feat: Add DropRules Support
  .tutone.yml
  pkg/nrqldroprules/example_basic_test.go
  pkg/nrqldroprules/nrqldroprules.go
  pkg/nrqldroprules/nrqldroprules_api.go
  pkg/nrqldroprules/nrqldroprules_integration_test.go
  pkg/nrqldroprules/types.go
Labels: enhancement, size:M

#670 chore(tutone): update generated code
  pkg/nrqldroprules/types.go
Labels: enhancement

#671 chore(changelog): Update CHANGELOG for v0.58.0
  CHANGELOG.md
  internal/version/version.go
Labels: bug, enhancement, priority:high, size:M

#681 fix(dashboards): Return rawConfiguration on get
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboards_api_integration_test.go
Labels: bug, priority:blocker, size:S

#682 chore(changelog): Update CHANGELOG for v0.58.1
  CHANGELOG.md
  internal/version/version.go
Labels: priority:blocker

#684 fix(dashboards): Prevent nil dereference on GetDashboardEntity
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboards_api_integration_test.go
Labels: bug, priority:high, size:S
